"""Shared column mixins for the ORM models.

Every core table has a UUID primary key and created_at / updated_at timestamps
(see docs/schema.md conventions). Rather than repeat those columns on every model,
they live here as mixins.

Design notes:
- UUID primary keys default to Postgres `gen_random_uuid()`, built into Postgres 13+
  so no extension is needed on the Postgres 16 image we run. UUIDs avoid cross-source
  id collisions when merging FootyStats, scraper, and manual-entry data.
- Timestamps are TIMESTAMPTZ (`DateTime(timezone=True)`) stored in UTC, with database
  defaults so inserts from any layer (app, pipeline, raw SQL) get consistent values.
"""

import uuid
from datetime import datetime

from sqlalchemy import DateTime, func, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column


class UUIDPrimaryKeyMixin:
    """A UUID primary key generated by the database."""

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )


class TimestampMixin:
    """created_at / updated_at, both database-managed."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )
